apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: k6sy-pod-gvisor-runtime
  name: k6sy-pod-gvisor-runtime
spec:
  runtimeClassName: k6sy-runtime-class
  containers:
  - image: nginx
    name: k6sy-pod-gvisor-runtime
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always